### PR TITLE
For StacDBReplayClient, translate obsgamestates contents from pre-2020 schema in StacDBHelper.selectOGSR

### PR DESCRIPTION
**Pull request by jdmonin**
The obsgamestates field schema was recently added to (commit 8818d74 in September). One side-effect is that if someone has a database dump from earlier, like human.sql in the repo, StacDBReplayClient can't replay it anymore because it's missing the new fields.

This PR lets StacDBHelper.selectOGSR recognize that situation and extract the playersResources array field out of the old schema's players array contents.

### CODE REVIEW

**Comment by morgangiraud** [comment]
Hi Jeremy,

Thanks for your PR, I have to say I was quite in a rush before the end of my internship and I didn't think everything through. 

LGTM!

**Comment by jdmonin** [comment]
Hi Morgan,

Very understandable :)

One related thing I noticed and didn't have a chance to follow up on: With this change, StacDBReplayClient runs OK except on console there's an exception in the MCTS code when it's sent the shorter player data array:

```
java.lang.ArrayIndexOutOfBoundsException: 25
		at mcts.game.catan.Catan.<init>(Catan.java:142)
		at soc.server.database.stac.StacDBToCatanInterface.generateGame(StacDBToCatanInterface.java:595)
		at soc.server.database.stac.StacDBToCatanInterface.generateGameFromDB(StacDBToCatanInterface.java:211)
```

So probably the array needs translating before it reaches that MCTS code, or in that code.

I might look at it in the future, but if you want to look sooner, go ahead.

**Comment by morgangiraud** [comment]
Hi Jeremy.

I've just noticed I might have not updated you on my current situation. Due to Covid related issues and cost cut, I did not get a PhD after my internship. I ended up just jobless and have to find new job opportunities so I will not keep contributing to the language grounding project, sadly. 

Anyway, I'll definitely keep an eye on the project for discussion and merges.

**Comment by jdmonin** [comment]
Hi Morgan,

Thanks for letting me know. This has been a tough year, and I hope things
are better for you soon. Sorry I haven't replied sooner.

Best wishes for your job search. From our interactions I know you do
interesting work, so hopefully there's good news soon.

Take care and happy new year!
-Jeremy

**Comment by morgangiraud** [comment]
Thanks for your words. Happy new year to you too!

Le jeu. 31 déc. 2020 à 21:56, Jeremy Monin <notifications@github.com> a
écrit :

> Hi Morgan,
>
> Thanks for letting me know. This has been a tough year, and I hope things
> are better for you soon. Sorry I haven't replied sooner.
>
> Best wishes for your job search. From our interactions I know you do
> interesting work, so hopefully there's good news soon.
>
> Take care and happy new year!
> -Jeremy
>
>
>

**Pull request merged**
